### ISSUE TITLE
[PE-D] Incorrect date for meal added

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-3/tp#186]
![image.png](https://raw.githubusercontent.com/KZQ1999/ped/main/files/cc3a7eca-68b8-4e7b-886b-6fe17e1de317.png)

When meal was added and date was given, the date of the entry added was not correct.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: KZQ1999/ped#1

**Comment by EdwardZYWang** [comment]
ug
