### ISSUE TITLE
[PE-D] Behaviour for adding a meal with invalid date is not specified. 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-3/tp#192]
When adding a meal with correct fields except for an invalid date, the error message shown is not catered to the actual error. 

![image.png](https://raw.githubusercontent.com/Alvinlj00/ped/main/files/82b98204-e721-46e3-93c9-6f69f5304852.png)

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: Alvinlj00/ped#2

**Comment by EdwardZYWang** [comment]
ug, the /c
