### ISSUE TITLE
[PE-D] Add meal when meal has not been taken yet

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-3/tp#193]
![image.png](https://raw.githubusercontent.com/Bobowoo2468/ped/main/files/8e0092b8-bb3a-4c10-81e5-4746f8f79684.png)

The date of add meal is before the meal was taken.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Bobowoo2468/ped#2

**Comment by EdwardZYWang** [comment]
ug
