### ISSUE TITLE
[PE-D] Exception not handled (suggestion)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-3/tp#194]
Acknowledged that an integer is prompted but if user accidentally input decimal it crashes and exception is not handled. A suggestion is to handle the exception is to prompt for another input.

![image.png](https://raw.githubusercontent.com/zonglun99/ped/main/files/f85455c5-e83d-48c0-baa5-3386cc73ec50.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: zonglun99/ped#2

**Comment by EdwardZYWang** [comment]
do we need to change the type of activity level and age to doubel? if so, we need to change integer.[arseint to doublt.parsefdouble

**Comment by EdwardZYWang** [comment]
need to catch exceptions for ui.get info and calculator
