### ISSUE TITLE
[PE-D] Deleted a meal from library but it now shows incorrect library count for meal

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-3/tp#199]
![image.png](https://raw.githubusercontent.com/KZQ1999/ped/main/files/77d251d9-e0ff-4f87-a2dd-a8a18fd93aee.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: KZQ1999/ped#5

**Comment by VishalJeyaram** [comment]
Issue fixed. Number of meals and fluids updates everytime a meal or fluid has been added.
