### ISSUE TITLE
[PE-D] Add functionality parse exception

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-3/tp#208]
![image.png](https://raw.githubusercontent.com/Bobowoo2468/ped/main/files/c4449273-ce81-41a8-a268-22f28a521e6c.png)

parses /c 230 20 as 230

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Bobowoo2468/ped#7

**Comment by EdwardZYWang** [comment]
add in UG, make sure it takes the first input
