### ISSUE TITLE
[PE-D] Listing all meals

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-3/tp#210]
As a user, I would like to know when I had the meal.

![image.png](https://raw.githubusercontent.com/Bobowoo2468/ped/main/files/9b8fb0f7-35d1-4cd6-8f81-edd96cd8299d.png)

However, I only can see that the Date is 'all'.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Bobowoo2468/ped#8

**Comment by VishalJeyaram** [comment]
Issue has been fixed. Now date shows the actual date instead of "all"
