### ISSUE TITLE
[PE-D] Storage files not loaded after issue #6

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-3/tp#218]
Upon closing and re running jar file after the bugs from issue 6, storage data are deleted.
![image.png](https://raw.githubusercontent.com/zonglun99/ped/main/files/acccba60-f224-4a36-92b2-3de494144089.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: zonglun99/ped#7

**Comment by EdwardZYWang** [comment]
uodate in UG to press y for loading storage. add comfirmation message
