### ISSUE TITLE
[PE-D] Index out of bound exception for delete not yet implemented, exits the user from the program.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-3/tp#220]
![image.png](https://raw.githubusercontent.com/Bobowoo2468/ped/main/files/c20efd91-132f-4f85-a02c-fbf1cd101aa9.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Bobowoo2468/ped#13

**Comment by VishalJeyaram** [comment]
Issue has been fixed. Exception will be thrown if index is out of range.
