### ISSUE TITLE
[PE-D] List command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-3/tp#227]
A `list` command list out everything. Not sure if it is intended since there are specified list commands such as `list weights`

![image.png](https://raw.githubusercontent.com/zonglun99/ped/main/files/c3127189-51d1-4030-b1d1-bbe4bc5f9a81.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: zonglun99/ped#9

**Comment by EdwardZYWang** [comment]
update help message and ug
